begin;

-- size chart seeded from the IKEA size chart PDF
insert into public.uniform_size_chart (category, size_label, chest_range, waist_range, hip_range, fit_note, sort_order) values
  ('shaped_tops', 'CD', '26.75-28.25 in', null, null, 'Shaped tops from IKEA size chart PDF', '1'),
  ('shaped_tops', 'EF', '30-31.5 in', null, null, 'Shaped tops from IKEA size chart PDF', '2'),
  ('shaped_tops', 'GH', '33-34.5 in', null, null, 'Shaped tops from IKEA size chart PDF', '3'),
  ('shaped_tops', 'IJ', '36.25-37.75 in', null, null, 'Shaped tops from IKEA size chart PDF', '4'),
  ('shaped_tops', 'KN', '39.5-41 in', null, null, 'Shaped tops from IKEA size chart PDF', '5'),
  ('shaped_tops', 'OP', '43.25-45.75 in', null, null, 'Shaped tops from IKEA size chart PDF', '6'),
  ('shaped_tops', 'QR', '48-50.5 in', null, null, 'Shaped tops from IKEA size chart PDF', '7'),
  ('shaped_tops', 'TU', '53.5-56.75 in', null, null, 'Shaped tops from IKEA size chart PDF', '8'),
  ('shaped_tops', 'VY', '60-63 in', null, null, 'Shaped tops from IKEA size chart PDF', '9'),
  ('straight_tops', 'CD', '31.5-33 in', null, null, 'Straight tops from IKEA size chart PDF', '1'),
  ('straight_tops', 'EF', '34.5-36.25 in', null, null, 'Straight tops from IKEA size chart PDF', '2'),
  ('straight_tops', 'GH', '37.75-39.5 in', null, null, 'Straight tops from IKEA size chart PDF', '3'),
  ('straight_tops', 'IJ', '41-42.5 in', null, null, 'Straight tops from IKEA size chart PDF', '4'),
  ('straight_tops', 'KN', '44-45.75 in', null, null, 'Straight tops from IKEA size chart PDF', '5'),
  ('straight_tops', 'OP', '48-50.5 in', null, null, 'Straight tops from IKEA size chart PDF', '6'),
  ('straight_tops', 'QR', '52.75-55 in', null, null, 'Straight tops from IKEA size chart PDF', '7'),
  ('straight_tops', 'TU', '58.25-61.5 in', null, null, 'Straight tops from IKEA size chart PDF', '8'),
  ('straight_tops', 'VY', '64.5-67.75 in', null, null, 'Straight tops from IKEA size chart PDF', '9'),
  ('shaped_bottoms', 'C', null, '20.5 in', '30 in', 'Measure waist and low hip; choose the biggest measurement', '1'),
  ('shaped_bottoms', 'D', null, '22 in', '31.5 in', 'Measure waist and low hip; choose the biggest measurement', '2'),
  ('shaped_bottoms', 'E', null, '23.5 in', '33 in', 'Measure waist and low hip; choose the biggest measurement', '3'),
  ('shaped_bottoms', 'F', null, '25.25 in', '34.5 in', 'Measure waist and low hip; choose the biggest measurement', '4'),
  ('shaped_bottoms', 'G', null, '26.75 in', '36.25 in', 'Measure waist and low hip; choose the biggest measurement', '5'),
  ('shaped_bottoms', 'H', null, '28.25 in', '37.75 in', 'Measure waist and low hip; choose the biggest measurement', '6'),
  ('shaped_bottoms', 'I', null, '30 in', '39.5 in', 'Measure waist and low hip; choose the biggest measurement', '7'),
  ('shaped_bottoms', 'J', null, '31.5 in', '41 in', 'Measure waist and low hip; choose the biggest measurement', '8'),
  ('shaped_bottoms', 'K', null, '33 in', '42.5 in', 'Measure waist and low hip; choose the biggest measurement', '9'),
  ('shaped_bottoms', 'N', null, '34.5 in', '44 in', 'Measure waist and low hip; choose the biggest measurement', '10'),
  ('shaped_bottoms', 'O', null, '37 in', '46.5 in', 'Measure waist and low hip; choose the biggest measurement', '11'),
  ('shaped_bottoms', 'P', null, '39.5 in', '48.75 in', 'Measure waist and low hip; choose the biggest measurement', '12'),
  ('shaped_bottoms', 'Q', null, '41.75 in', '51.25 in', 'Measure waist and low hip; choose the biggest measurement', '13'),
  ('shaped_bottoms', 'R', null, '44 in', '53.5 in', 'Measure waist and low hip; choose the biggest measurement', '14'),
  ('shaped_bottoms', 'T', null, '47.25 in', '56.75 in', 'Measure waist and low hip; choose the biggest measurement', '15'),
  ('shaped_bottoms', 'U', null, '50.5 in', '60 in', 'Measure waist and low hip; choose the biggest measurement', '16'),
  ('shaped_bottoms', 'V', null, '53.5 in', '63 in', 'Measure waist and low hip; choose the biggest measurement', '17'),
  ('shaped_bottoms', 'Y', null, '56.75 in', '66.25 in', 'Measure waist and low hip; choose the biggest measurement', '18'),
  ('straight_bottoms', 'C', null, '26.75 in', null, 'Straight bottoms use waist measurement', '1'),
  ('straight_bottoms', 'D', null, '28.25 in', null, 'Straight bottoms use waist measurement', '2'),
  ('straight_bottoms', 'E', null, '30 in', null, 'Straight bottoms use waist measurement', '3'),
  ('straight_bottoms', 'F', null, '31.5 in', null, 'Straight bottoms use waist measurement', '4'),
  ('straight_bottoms', 'G', null, '33 in', null, 'Straight bottoms use waist measurement', '5'),
  ('straight_bottoms', 'H', null, '34.5 in', null, 'Straight bottoms use waist measurement', '6'),
  ('straight_bottoms', 'I', null, '36.25 in', null, 'Straight bottoms use waist measurement', '7'),
  ('straight_bottoms', 'J', null, '37.75 in', null, 'Straight bottoms use waist measurement', '8'),
  ('straight_bottoms', 'K', null, '39.5 in', null, 'Straight bottoms use waist measurement', '9'),
  ('straight_bottoms', 'N', null, '41 in', null, 'Straight bottoms use waist measurement', '10'),
  ('straight_bottoms', 'O', null, '43.25 in', null, 'Straight bottoms use waist measurement', '11'),
  ('straight_bottoms', 'P', null, '45.75 in', null, 'Straight bottoms use waist measurement', '12'),
  ('straight_bottoms', 'Q', null, '48 in', null, 'Straight bottoms use waist measurement', '13'),
  ('straight_bottoms', 'R', null, '50.5 in', null, 'Straight bottoms use waist measurement', '14'),
  ('straight_bottoms', 'T', null, '53.5 in', null, 'Straight bottoms use waist measurement', '15'),
  ('straight_bottoms', 'U', null, '56.75 in', null, 'Straight bottoms use waist measurement', '16'),
  ('straight_bottoms', 'V', null, '60 in', null, 'Straight bottoms use waist measurement', '17'),
  ('straight_bottoms', 'Y', null, '63 in', null, 'Straight bottoms use waist measurement', '18'),
  ('shaped_tops_single', 'C', null, null, null, 'Single-size top reference', '1'),
  ('straight_tops_single', 'C', null, null, null, 'Single-size top reference', '1'),
  ('shaped_tops_single', 'D', null, null, null, 'Single-size top reference', '2'),
  ('straight_tops_single', 'D', null, null, null, 'Single-size top reference', '2'),
  ('shaped_tops_single', 'E', null, null, null, 'Single-size top reference', '3'),
  ('straight_tops_single', 'E', null, null, null, 'Single-size top reference', '3'),
  ('shaped_tops_single', 'F', null, null, null, 'Single-size top reference', '4'),
  ('straight_tops_single', 'F', null, null, null, 'Single-size top reference', '4'),
  ('shaped_tops_single', 'G', null, null, null, 'Single-size top reference', '5'),
  ('straight_tops_single', 'G', null, null, null, 'Single-size top reference', '5'),
  ('shaped_tops_single', 'H', null, null, null, 'Single-size top reference', '6'),
  ('straight_tops_single', 'H', null, null, null, 'Single-size top reference', '6'),
  ('shaped_tops_single', 'I', null, null, null, 'Single-size top reference', '7'),
  ('straight_tops_single', 'I', null, null, null, 'Single-size top reference', '7'),
  ('shaped_tops_single', 'J', null, null, null, 'Single-size top reference', '8'),
  ('straight_tops_single', 'J', null, null, null, 'Single-size top reference', '8'),
  ('shaped_tops_single', 'K', null, null, null, 'Single-size top reference', '9'),
  ('straight_tops_single', 'K', null, null, null, 'Single-size top reference', '9'),
  ('shaped_tops_single', 'N', null, null, null, 'Single-size top reference', '10'),
  ('straight_tops_single', 'N', null, null, null, 'Single-size top reference', '10'),
  ('shaped_tops_single', 'O', null, null, null, 'Single-size top reference', '11'),
  ('straight_tops_single', 'O', null, null, null, 'Single-size top reference', '11'),
  ('shaped_tops_single', 'P', null, null, null, 'Single-size top reference', '12'),
  ('straight_tops_single', 'P', null, null, null, 'Single-size top reference', '12'),
  ('shaped_tops_single', 'Q', null, null, null, 'Single-size top reference', '13'),
  ('straight_tops_single', 'Q', null, null, null, 'Single-size top reference', '13'),
  ('shaped_tops_single', 'R', null, null, null, 'Single-size top reference', '14'),
  ('straight_tops_single', 'R', null, null, null, 'Single-size top reference', '14'),
  ('shaped_tops_single', 'T', null, null, null, 'Single-size top reference', '15'),
  ('straight_tops_single', 'T', null, null, null, 'Single-size top reference', '15'),
  ('shaped_tops_single', 'U', null, null, null, 'Single-size top reference', '16'),
  ('straight_tops_single', 'U', null, null, null, 'Single-size top reference', '16'),
  ('shaped_tops_single', 'V', null, null, null, 'Single-size top reference', '17'),
  ('straight_tops_single', 'V', null, null, null, 'Single-size top reference', '17'),
  ('shaped_tops_single', 'Y', null, null, null, 'Single-size top reference', '18'),
  ('straight_tops_single', 'Y', null, null, null, 'Single-size top reference', '18'),
  ('accessories', 'ONE SIZE', null, null, null, 'Beanie and many accessories use one size', '1'),
  ('accessories', 'C-J', null, null, null, 'Apron size range C-J', '2'),
  ('accessories', 'K-Y', null, null, null, 'Apron size range K-Y', '3');

-- sample employee directory rows for testing the public request page
insert into public.employees (
  employee_id, full_name, ikea_email, department, job_title, location, size_top, size_bottom, imported_at
) values
  ('100001', 'Amanda Silva', 'amanda.silva@ikea.com', 'Fulfillment Operations', 'Co-worker', 'Toronto', 'GH', 'J', now()),
  ('100002', 'Denis Costa', 'denis.costa@ikea.com', 'Fulfillment Operations', 'Co-worker', 'Toronto', 'IJ', 'K', now()),
  ('100003', 'Dayana Rocha', 'dayana.rocha@ikea.com', 'Customer Service', 'Co-worker', 'Toronto', 'EF', 'H', now()),
  ('100004', 'Andrew Plumer', 'andrew.plumer@ikea.com', 'IKEA Food', 'Co-worker', 'Toronto', 'KN', 'N', now())
on conflict (employee_id) do nothing;

-- deduplicated inventory imported from Uniform Inventory Count.xlsx
insert into public.inventory_items (
  inventory_key, sku, product_type, layer, colour, fit, sleeve, style, size,
  stock_quantity, reserved_quantity, ordered_quantity, dry_cleaned_quantity, reorder_level, unit, is_active, location, notes
) values
  ('4-pocket-pants-shaped-c-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'C', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-c-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'C', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-c-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'C', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-d-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'D', 5, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-d-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'D', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-d-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'D', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-e-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'E', 10, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-e-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'E', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-e-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'E', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-f-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'F', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-f-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'F', 5, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-f-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'F', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-g-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'G', 7, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-g-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'G', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-g-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'G', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-h-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'H', 13, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-h-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'H', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-h-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'H', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-i-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'I', 8, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-i-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'I', 7, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-i-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'I', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-j-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'J', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-j-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'J', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-j-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-k-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'K', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-k-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'K', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-k-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'K', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-n-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'N', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-n-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-n-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-o-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-o-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-o-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-p-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-p-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'P', 5, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-p-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-q-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'Q', 7, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-q-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'Q', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-q-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'Q', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-r-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'R', 6, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-r-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'R', 9, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-r-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-t-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-t-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-t-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'T', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-u-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'U', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-u-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-u-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-v-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'V', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-v-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'V', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-v-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'V', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-shaped-y-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, '4-Pocket Pants', 'Y', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-shaped-y-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Lightweight Pants', 'Y', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-shaped-y-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Multi-pocket Pants', 'Y', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-c-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'C', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-c-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'C', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-c-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'C', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-d-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'D', 13, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-d-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'D', 10, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-d-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'D', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-e-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'E', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-e-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'E', 11, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-e-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'E', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-f-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'F', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-f-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'F', 7, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-f-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'F', 5, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-g-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'G', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-g-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'G', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-g-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'G', 5, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-h-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'H', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-h-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'H', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-h-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'H', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-i-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'I', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-i-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'I', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-i-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'I', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-j-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-j-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-j-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'J', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-k-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'K', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-k-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'K', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-k-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'K', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-n-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'N', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-n-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'N', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-n-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'N', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-o-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-o-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-o-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'O', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-p-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-p-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'P', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-p-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'P', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-q-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'Q', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-q-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'Q', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-q-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'Q', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-r-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'R', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-r-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-r-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-t-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-t-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-t-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-u-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-u-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-u-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-v-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'V', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-v-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'V', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-v-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'V', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('4-pocket-pants-straight-y-uniform-room', null, '4-Pocket Pants', 'Bottoms', 'Standard', 'Straight', null, '4-Pocket Pants', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('lightweight-pants-straight-y-uniform-room', null, 'Lightweight Pants', 'Bottoms', 'Standard', 'Straight', null, 'Lightweight Pants', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-pants-straight-y-uniform-room', null, 'Multi-pocket Pants', 'Bottoms', 'Standard', 'Straight', null, 'Multi-pocket Pants', 'Y', 5, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-c-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'C', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-d-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'D', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-e-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'E', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-f-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'F', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-g-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'G', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-h-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'H', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-i-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'I', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-j-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-k-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'K', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-n-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-o-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-p-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-q-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'Q', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-r-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-t-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-u-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-v-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'V', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-shaped-y-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Shaped', null, 'Kitchen Pants', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-c-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'C', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-d-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'D', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-e-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'E', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-f-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'F', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-g-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'G', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-h-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'H', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-i-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'I', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-j-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-k-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'K', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-n-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-o-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-p-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-q-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'Q', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-r-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-t-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-u-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-v-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'V', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-pants-straight-y-uniform-room', null, 'Kitchen Pants', 'Bottoms', 'Standard', 'Straight', null, 'Kitchen Pants', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-cd-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'CD', 15, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-cd-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'CD', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-ef-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'EF', 40, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-ef-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'EF', 0, 0, 0, 2, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-gh-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'GH', 30, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-gh-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'GH', 14, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-ij-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'IJ', 31, 0, 0, 4, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-ij-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'IJ', 9, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-kn-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'KN', 46, 0, 0, 2, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-kn-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'KN', 31, 0, 0, 6, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-op-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-op-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'OP', 42, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-qr-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'QR', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-qr-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'QR', 8, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-tu-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-tu-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-shaped-vy-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-shaped-vy-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'VY', 42, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-cd-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'CD', 2, 0, 0, 2, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-cd-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'CD', 5, 0, 0, 1, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-ef-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'EF', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-ef-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'EF', 37, 0, 0, 1, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-gh-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'GH', 0, 0, 0, 3, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-gh-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'GH', 10, 0, 0, 3, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-ij-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'IJ', 12, 0, 0, 1, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-ij-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'IJ', 23, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-kn-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'KN', 7, 0, 0, 1, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-kn-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'KN', 17, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-op-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-op-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-qr-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'QR', 5, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-qr-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'QR', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-tu-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-tu-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('short-sleeve-t-shirt-straight-vy-uniform-room', null, 'Short-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Short Sleeve', 'Short-Sleeve T-Shirt', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-t-shirt-straight-vy-uniform-room', null, 'Long-Sleeve T-Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Long-Sleeve T-Shirt', 'VY', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-cd-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'CD', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-cd-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'CD', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-ef-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'EF', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-ef-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'EF', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-gh-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'GH', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-gh-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'GH', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-ij-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'IJ', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-ij-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'IJ', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-kn-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'KN', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-kn-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'KN', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-op-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-op-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-qr-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'QR', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-qr-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'QR', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-tu-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-tu-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-shaped-vy-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Shaped', null, 'Long-Sleeve Sweater', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('long-sleeve-sweater-straight-vy-uniform-room', null, 'Long-Sleeve Sweater', 'Second Layer', 'Standard', 'Straight', null, 'Long-Sleeve Sweater', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-cd-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'CD', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-cd-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'CD', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-c-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'C', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-ef-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'EF', 6, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-ef-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'EF', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-d-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'D', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-gh-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'GH', 6, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-gh-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'GH', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-f-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'F', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-ij-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'IJ', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-ij-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'IJ', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-h-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'H', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-kn-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'KN', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-kn-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'KN', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-j-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'J', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-op-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'OP', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-op-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-k-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'K', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-qr-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'QR', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-qr-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'QR', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-n-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'N', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-tu-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-tu-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-o-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'O', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-vy-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'VY', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-shaped-vy-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Multi-pocket Jackets', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-p-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'P', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-q-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'Q', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-cd-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'CD', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-cd-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'CD', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-r-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-ef-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'EF', 10, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-ef-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'EF', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-u-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-gh-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'GH', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-gh-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'GH', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-v-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'V', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-ij-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'IJ', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-ij-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'IJ', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-shaped-y-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Shaped', null, 'Vests', 'Y', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-kn-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'KN', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-kn-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'KN', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-op-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'OP', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-op-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-d-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'D', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-qr-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'QR', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-qr-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'QR', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-e-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'E', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-tu-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-tu-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-f-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'F', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-vy-uniform-room', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('multi-pocket-jackets-straight-vy-uniform-room', null, 'Multi-pocket Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Multi-pocket Jackets', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-h-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'H', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-i-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'I', 3, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-j-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'J', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-k-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'K', 2, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-n-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-p-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'P', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-r-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'R', 1, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-u-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-v-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'V', 4, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('vests-straight-y-uniform-room', null, 'Vests', 'Outerwear', 'Standard', 'Straight', null, 'Vests', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-d-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'D', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-f-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'F', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-h-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'H', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-j-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-n-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-p-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-r-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-u-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-shaped-y-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Kitchen Jackets', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-d-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'D', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-f-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'F', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-h-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'H', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-j-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-n-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-p-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-r-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-u-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('kitchen-jackets-straight-y-uniform-room', null, 'Kitchen Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Kitchen Jackets', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-cd-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'CD', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-ef-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'EF', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-gh-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'GH', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-ij-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'IJ', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-kn-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'KN', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-op-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-qr-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'QR', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-tu-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-shaped-vy-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Shaped', null, 'Full-Zip Jackets', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-cd-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'CD', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-ef-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'EF', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-gh-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'GH', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-ij-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'IJ', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-kn-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'KN', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-op-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'OP', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-qr-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'QR', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-tu-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'TU', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('full-zip-jackets-straight-vy-empu', null, 'Full-Zip Jackets', 'Outerwear', 'Standard', 'Straight', null, 'Full-Zip Jackets', 'VY', 0, 0, 0, 0, 2, 'pcs', true, 'EMPU', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-c-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'C', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-c-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'C', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-d-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'D', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-d-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'D', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-e-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'E', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-e-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'E', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-f-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'F', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-f-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'F', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-g-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'G', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-g-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'G', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-h-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'H', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-h-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'H', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-i-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'I', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-i-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'I', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-j-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-j-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'J', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-k-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'K', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-k-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'K', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-n-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-n-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'N', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-o-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-o-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'O', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-p-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-p-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'P', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-q-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'Q', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-q-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'Q', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-r-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-r-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'R', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-t-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-t-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'T', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-u-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-u-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'U', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-v-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'V', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-v-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'V', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-shaped-y-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Shaped', 'Long Sleeve', 'Button-Up Shirt', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('button-up-shirt-straight-y-uniform-room', null, 'Button-Up Shirt', 'Tops', 'Standard', 'Straight', 'Long Sleeve', 'Button-Up Shirt', 'Y', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('landyard-nofit-one-size-uniform-room', null, 'Landyard', 'Accessories', 'Standard', null, null, 'Landyard', 'ONE SIZE', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('name-tag-nofit-one-size-uniform-room', null, 'Name Tag', 'Accessories', 'Standard', null, null, 'Name Tag', 'ONE SIZE', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('badge-holder-nofit-one-size-uniform-room', null, 'Badge Holder', 'Accessories', 'Standard', null, null, 'Badge Holder', 'ONE SIZE', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('beanie-nofit-one-size-uniform-room', null, 'Beanie', 'Accessories', 'Standard', null, null, 'Beanie', 'ONE SIZE', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('belt-ring-nofit-one-size-uniform-room', null, 'Belt Ring', 'Accessories', 'Standard', null, null, 'Belt Ring', 'ONE SIZE', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('belt-nofit-one-size-uniform-room', null, 'Belt', 'Accessories', 'Standard', null, null, 'Belt', 'ONE SIZE', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('scarf-nofit-one-size-n-a', null, 'Scarf', 'Accessories', 'Standard', null, null, 'Scarf', 'ONE SIZE', 0, 0, 0, 0, 2, 'pcs', true, 'N/A', 'Imported from Uniform Inventory Count.xlsx'),
  ('tool-pouch-nofit-one-size-uniform-room', null, 'Tool Pouch', 'Accessories', 'Standard', null, null, 'Tool Pouch', 'ONE SIZE', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('bib-apron-c-j-nofit-c-j-n-a', null, 'Bib Apron C/J', 'Accessories', 'Standard', null, null, 'Bib Apron C/J', 'C-J', 0, 0, 0, 0, 2, 'pcs', true, 'N/A', 'Imported from Uniform Inventory Count.xlsx'),
  ('bib-apron-k-y-nofit-k-y-n-a', null, 'Bib Apron K/Y', 'Accessories', 'Standard', null, null, 'Bib Apron K/Y', 'K-Y', 0, 0, 0, 0, 2, 'pcs', true, 'N/A', 'Imported from Uniform Inventory Count.xlsx'),
  ('waist-apron-cj-nofit-c-j-n-a', null, 'Waist Apron CJ', 'Accessories', 'Standard', null, null, 'Waist Apron CJ', 'C-J', 0, 0, 0, 0, 2, 'pcs', true, 'N/A', 'Imported from Uniform Inventory Count.xlsx'),
  ('waist-apron-ky-nofit-k-y-n-a', null, 'Waist Apron KY', 'Accessories', 'Standard', null, null, 'Waist Apron KY', 'K-Y', 0, 0, 0, 0, 2, 'pcs', true, 'N/A', 'Imported from Uniform Inventory Count.xlsx'),
  ('bandana-55-58cm-nofit-55-58-uniform-room', null, 'Bandana 55-58CM', 'Accessories', 'Standard', null, null, 'Bandana 55-58CM', '55-58', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('bandana-58-61cm-nofit-58-61-uniform-room', null, 'Bandana 58-61CM', 'Accessories', 'Standard', null, null, 'Bandana 58-61CM', '58-61', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('pillar-hat-55cm-nofit-55-uniform-room', null, 'Pillar Hat 55CM', 'Accessories', 'Standard', null, null, 'Pillar Hat 55CM', '55', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('pillar-hat-58cm-nofit-58-uniform-room', null, 'Pillar Hat 58CM', 'Accessories', 'Standard', null, null, 'Pillar Hat 58CM', '58', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx'),
  ('pillar-hat-61cm-nofit-61-uniform-room', null, 'Pillar Hat 61CM', 'Accessories', 'Standard', null, null, 'Pillar Hat 61CM', '61', 0, 0, 0, 0, 2, 'pcs', true, 'Uniform Room', 'Imported from Uniform Inventory Count.xlsx')
on conflict (inventory_key) do update set
  stock_quantity = excluded.stock_quantity,
  ordered_quantity = excluded.ordered_quantity,
  dry_cleaned_quantity = excluded.dry_cleaned_quantity,
  layer = excluded.layer,
  colour = excluded.colour,
  fit = excluded.fit,
  sleeve = excluded.sleeve,
  style = excluded.style,
  size = excluded.size,
  location = excluded.location,
  notes = excluded.notes,
  updated_at = now();

insert into public.inventory_stock_movements (inventory_item_id, qty_delta, movement_type, reason)
select id, stock_quantity, 'seed', 'Initial load from Uniform Inventory Count.xlsx'
from public.inventory_items
where stock_quantity > 0
on conflict do nothing;

commit;
